### ISSUE TITLE
support of NUC140

### ISSUE THREAD

**Issue by burrbull** [OpenNuvoton/OpenOCD-Nuvoton#7]
I have board Nu-LB-NUC140 V2.0 (with Nu-Link on board).

Can I connect to it with openocd and if so what cfg files I should pass?

**Comment by burrbull** [comment]
Sorry. I just need set `udev` rules.

**Comment by burrbull** [comment]
I've connected to device, but I can't understand what linker script (memory layout) I should use?

**Comment by ZaleYu** [comment]
Hi burrbull:
Please refer to the following links:
http://www.scoberlin.de/content/media/http/informatik/gcc_docs/ld_3.html
https://sourceware.org/binutils/docs/ld/Scripts.html

The linker script should be decided by your project. Because your question is not an issue of OpenOCD, I closed this issue.

Sincerely, 
Zale Yu
